pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from ..forms import AnswerForm

from .. import db 

from ..models import Question, Answer

from .auth_views import login_required # 로그인 데코레이터를 사용하기 위해 import


#answer_views.py 파일이 answer라는 이름의 블루프린트 파일임을 나타냄
bp = Blueprint('answer',__name__,url_prefix='/answer')

#답변 등록 함수
@bp.route('/create/<int:question_id>',methods=('POST',))
#답변 저장 템플릿에 있는 form 태그의 action 속성에 해당하는 URL을 나타낸다
@login_required #로그인 애너테이션 적용
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    #name 속성이 content인 form 태그의 데이터를 request.form['content']로 가져온다
    #답변 저장 버튼을 누르면 POST 방식으로 전송되었으면 form.validate_on_submit()이 참이 되어 답변을 저장한다
    if form.validate_on_submit():
        content=request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect('{}#answer_{}'.format(url_for('question.detail',question_id=question_id),answer.id))
    return render_template('question/question_detail.html',question=question,form=form)

#답변 수정 함수
@bp.route('/modify/<int:answer_id>',methods=('GET','POST'))
@login_required #답변 수정 시 로그인 여부 확인
def modify(answer_id):
    answer=Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정 권한이 없습니다.')# 답변 수정 권한이 없는 경우 오류 메세지 출력
        return redirect(url_for('question.detail',question_id = answer.quetion.id))
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect('{}#answer_{}'.format(url_for('question.detail',question_id = answer.question.id),answer.id))
    else:
        form = AnswerForm(obj=answer) #데이터베이스에서 조회한 답변 객체를 obj로 설정하여 폼에 초기값을 설정
    return render_template('answer/answer_form.html',answer=answer,form=form) #GET 방식이면 답변 수정 페이지 렌더링

#답변 삭제 함수
@bp.route('/delete/<int:answer_id>')
@login_required #답변 삭제 시 로그인 여부 확인
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제 권한이 없습니다') #답변 삭제 권한이 없는 경우 오류 메세지 출력
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id)) #답변 삭제 후 질문 상세 페이지로 리다이렉트

pybo/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, render_template, g, request, flash 
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import CommentForm
from pybo.models import Question, Comment, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('comment',__name__,url_prefix='/comment')

#질문 댓글 등록 함수 
@bp.route('/create/question/<int:question_id>',methods=('GET','POST'))
@login_required
def create_question(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user = g.user,content=form.content.data, create_date=datetime.now(), question=question)
        db.session.add(comment)
        db.session.commit()
        return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=question_id),comment.id))
    return render_template('comment/comment_form.html',form=form)

#질문 댓글 수정 함수
@bp.route('/modify/question/<int:comment_id>',methods=('GET','POST'))
@login_required
def modify_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('question.detail',question_id=comment.question.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now() #수정일시 저장
            db.session.commit()
            return redirect('{}#comment_{}'.foramt(url_for('question.detail',question_id=comment.question.id),comment.id))
    else: #GET 요청일 경우 기존 댓글을 조회
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html',form=form)

#질문 댓글 삭제 함수 
@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
    comment=Comment.query.get_or_404(comment_id)
    question_id = comment.question.id
    if g.user != comment.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail',question_id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id))

#답변 댓글 생성 함수
@bp.route('/create/answer/<int:answer_id>',methods=('GET','POST'))
@login_required
def create_answer(answer_id):
    form = CommentForm()
    answer = Answer.query.get_or_404(answer_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), answer=answer)
        db.session.add(comment)
        db.session.commit()
        return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=answer.question.id),comment.id))
    return render_template('comment/comment_form.html',form=form)

#답변 댓글 수정 함수
@bp.route('/modify/answer/<int:comment_id>',methods=('GET','POST'))
@login_required
def modify_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail',question_id=comment.answer.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=comment.answer.question.id),comment.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html',form=form)

#답변 댓글 삭제 함수
@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
    comment=Comment.query.get_or_404(comment_id)
    question_id=comment.answer.question.id
    if g.user != comment.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail',question_id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint , render_template, request, redirect, url_for, g, flash

from pybo.models import Question

from ..forms import QuestionForm, AnswerForm 

from werkzeug.utils import redirect

from sqlalchemy import func 

from ..import db

from pybo.views.auth_views import login_required # 로그인 데코레이터를 사용하기 위해 import

from ..models import Question, Answer, User, question_voter

bp=Blueprint('question',__name__,url_prefix='/question')

@bp.route('/list/')
def _list():
    #입력 파라미터
    page = request.args.get('page',type=int,default=1) #페이지
    kw = request.args.get('kw',type=str,default='') #검색어
    so = request.args.get('so',type=str,default='recent') #정렬기준

    #정렬
    if so == 'recommend': # 추천순으로 정렬
        sub_query = db.session.query(
            question_voter.c.question_id, func.count('*').label('num_voter')) \
            .group_by(question_voter.c.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query,Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_voter.desc(),Question.create_date.desc())
        
    elif so == 'popular' : #답변이 많은 질문 순으로 정렬
        sub_query = db.session.query(
            Answer.question_id, func.count('*').label('num_answer')) \
                .group_by(Answer.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id==sub_query.c.question_id) \
            .order_by(sub_query.c.num_answer.desc(),Question.create_date.desc())
    
    else: #최근 등록된 질문 순으로 정렬
        question_list = Question.query.order_by(Question.create_date.desc())
        
    #조회
    if kw: #검색어가 있을 경우 질문 제목, 내용, 작성자, 답변 내용, 답변 작성자 항목에서 OR 조건으로 검색
        search='%%{}%%'.format(kw) #검색어를 포함하는 질문을 찾기 위해 %%로 감싸줌

        sub_query = db.session.query(
            Answer.question_id, Answer.content, User.username).join(
                User, Answer.user_id==User.id).subquery()
        
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(
                Question.subject.ilike(search) | # 제목
                Question.content.ilike(search) | # 내용
                User.username.ilike(search) | # 질문 작성자
                sub_query.c.content.ilike(search) | #답변 내용
                sub_query.c.username.ilike(search) #답변 작성자
                ) \
            .distinct() 
        
    # 페이징
    question_list = question_list.paginate(page=page,per_page=10)
    return render_template('question/question_list.html',
                           question_list=question_list,page=page,kw=kw)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form=AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html',question=question,form=form)

#질문 등록 함수
@bp.route('/create/', methods=('GET','POST'))
@login_required #로그인 애너테이션 적용, 로그인 여부 확인
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit(): #폼 데이터의 정합성 검사
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index')) #POST 방식이면 데이터 저장, 데이터 저장이 완료되면 main.index로 리다이렉트
    return render_template('question/question_form.html',form=form) # GET 방식으면 질문 등록 페이지 렌더링

#질문 수정 함수
@bp.route('/modify/<int:question_id>',methods=('GET','POST'))
@login_required #질문 수정 시 로그인 여부 확인
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정 권한이 없습니다.') # 수정 권한이 없을 경우 오류 메시지 출력
        return redirect(url_for('question.detail',question_id=question_id))
    if request.method == 'POST': #POST 방식이면 질문 수정 처리
        form  = QuestionForm()
        if form.validate_on_submit(): #폼 데이터의 검증
            form.populate_obj(question) #form의 데이터를 question 객체에 저장
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail',question_id=question_id))
    else:
        form = QuestionForm(obj=question)# 데이터베이스에서 조회한 질문 객체를 obj로 설정하여 폼에 초기값을 설정
    return render_template('question/question_form.html',form=form) #GET 방식이면 질문 수정 페이지 렌더링

#질문 삭제 함수
@bp.route('/delete/<int:question_id>')
@login_required #질문 삭제 시 로그인 여부 확인
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제 권한이 없습니다.') # 삭제 권한이 없을 경우 오류 메세지 출력
        return redirect(url_for('quetion.detail',question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/vote_views.py
from flask import Blueprint, url_for, flash, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('vote',__name__,url_prefix='/vote')

#질문 추천 함수
@bp.route('/question/<int:question_id>/')
@login_required
def question(question_id):
    _question=Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할 수 없습니다.')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id))

#답변 추천 함수
@bp.route('/answer/<int:answer_id>/')
@login_required
def answer(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('본인이 작성한 글은 추천할 수 없습니다.')
    else:
        _answer.voter.append(g.uer)
        db.session.commit()
    return redirect(url_for('question.detail',question_id=_answer.question.id))

pybo/templates/question/question_detail.html
{%extends 'base.html'%}
{%block content%}
<div class="container my-3">
    <!--alert 메세지를 위쪽으로 배치-->
    {%for message in get_flashed_messages()%}
    <div class="alert alert-danger" role="alert">
        {{message}}
    </div>
    {%endfor%}
<!--my-3 : 위아래(m은 margin, y는 y축을 의미) 방향으로 부트스트랩 기준 3 정도의 마진
    py-2 : 위아래 방향으로 부트스트랩 기준 2 정도의 패딩
    p-2: 상하좌우 방향으로 부트스트랩 기준 2 정도의 패딩  -->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="row my-3">
    <!--질문 추천 버튼-->
        <div class="col-1"><!--추천 영역 : col-1 클래스를 사용하여 추천 영역의 너비 크기를 1/12로 적용-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{question.voter|length}}
            </div>
            <a href="#" data-uri="{{url_for('vote.question',question_id=question.id)}}" class="recommend btn btn-sm btn-secondary btn-block my-1">
                추천
            </a>
        </div>
        <div class="col-11"><!--질문 영역 : col-11 클래스를 사용하여 질문 영역의 너비 크기를 11/12로 적용-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        <!--질문에 마크다운 기능 적용-->
                        {{question.content|markdown}}
                    </div>
                    <div clas="d-flex justify-content-end">
                        <!--질문 수정일자 표시-->
                        {%if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{question.modify_date|datetime}}</div>
                        </div>
                        {%endif%}
                        <div class="badge badge-light p-2 text-left">
                            <!--질문 등록자 표시-->
                            <div class="mb-2">{{question.user.username}}</div>
                            <!--질문 등록일자 표시-->
                            <div>{{question.create_date|datetime}}</div>
                        </div>
                    </div>
                    <!--질문 수정,삭제 버튼-->
                    {% if g.user == question.user %}
                    <div class="my-3">
                        <!--질문 수정-->
                        <a href="{{url_for('question.modify',question_id=question.id)}}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <!--질문 삭제-->
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{url_for('question.delete',question_id=question.id)}}">삭제</a>
                    </div>
                    {% endif %} 
                    <!--질문 댓글 버튼-->
                    {% if question.comment_set|length > 0 %}
                    <div class="mt-3">
                    {%for comment in question.comment_set %}
                        <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{comment.content}}</span>
                            <span> - {{comment.user.username}}, {{comment.create_date|datetime}}
                                {%if comment.modify_date%}
                                (수정:{{comment.modify_date|datetime}})
                                {%endif%}
                            </span>
                            {% if g.user==comment.user %}
                            <a href="{{url_for('comment.modify_question',comment_id=comment.id)}}" class="small">수정</a>
                            <a href="#" class="small delete" data-uri="{{url_for('comment.delete_question',comment_id=comment.id)}}">삭제</a>
                            {%endif%}
                        </div>
                    {%endfor%}
                    </div>
                    {%endif%}
                    <div>
                        <a href="{{url_for('comment.create_question',question_id=question.id)}}" class="small"><small>댓글 추가..</small></small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set|length}}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set %}
    <a name="answer_{{answer.id}}"></a>
    <div class="row my-3">
        <div class="col-1"><!--답변 추천 영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{answer.voter|length}}
            </div>
            <a href="#" data-uri="{{url_for('vote.answer',answer_id=answer.id)}}" class="recommend btn btn-secondary btn-block my-1">
                추천
            </a>
        </div>
        <div class="col-11"><!--답변 영역-->
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text">
                        <!--답변에 마크다운 기능 적용-->
                        {{answer.content|markdown}}
                    </div>
                    <div class= "d-flex justify-content-end">
                        <!--답변 수정일자 표시-->
                        {%if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{answer.modify_date|datetime}}</div>
                        </div>
                        {%endif%}
                        <div class="badge badge-light p-2 text-left">
                            <!--답변 등록자 표시-->
                            <div class="mb-2">{{answer.user.username}}</div>
                            <!--답변 등록일자 표시-->
                            <div>{{answer.create_date|datetime}}</div>
                        </div>
                    </div>
                    <!--질문 답변 수정,삭제 버튼-->
                    {%if g.user == answer.user %}
                    <div class="my-3">
                        <!--답변 수정-->
                        <a href="{{url_for('answer.modify',answer_id=answer.id)}}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <!--답변 삭제-->
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{{url_for('answer.delete',answer_id=answer.id)}}">삭제</a>
                    </div>
                    {%endif%}
                    <!--답변 댓글 등록-->     
                        {%if answer.comment_set|length > 0 %}
                        <div class="mt-3">
                            {%for comment in answer.comment_set%}
                                <a name="comment_{{comment.id}}"></a>
                                <div class="comment py-2 text-muted">
                                    <span class="white-space: pre-line;">
                                        {{comment.content}}
                                    </span>
                                    <span>
                                        - {{comment.user.username}}, {{comment.create_date|datetime}}
                                        {%if comment.modify_date%}
                                        (수정:{{comment.modify_date|datetime}})
                                        {%endif%}
                                    </span>
                                    {%if g.user==comment.user%}
                                    <a href="{{url_for('comment.modify_answer',comment_id=comment.id)}}" class="small">수정</a>
                                    <a href="#" class="small delete" data-uri="{{url_for('comment.delete_answer',comment_id=comment.id)}}">삭제</a>
                                    {%endif%}
                                </div>
                        {%endfor%}
                        </div>
                        {%endif%}
                        <div>
                            <a href="{{url_for('comment.create_answer',answer_id=answer.id)}}" class="small"><small>댓글 추가 ..</small></a>
                        </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{url_for('answer.create',question_id=question.id)}}" method="post" class="my-3">
        {{form.csrf_token}}
        <!--오류 표시 시작-->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{form[field].label}}</strong>: {{', '.join(errors)}}
        </div> 
        {%endfor%}

        <!--오류 표시 끝-->
        <div class="form-group">
            <!--로그아웃 상태에서 답변 등록 비활성화-->
            <textarea {% if not g.user %} disabled {% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div> 
{%endblock%}
{%block script%}
<script type="text/javascript">
$(document).ready(function(){
    //삭제 버튼 클릭 시 확인 메세지 출력
    $(".delete").on('click',function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href=$(this).data("uri")
        }
    });

    //추천 버튼 클릭 시 확인 메세지 출력
    $(".recommend").on('click',function(){
        if(confirm("추천하시겠습니까?")){
            location.href=$(this).data("uri");
        }
    });
});
</script>
{%endblock%}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="containter">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{form.csrf_token}}
        <!--오류표시 시작-->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{form[field].label}}</strong>: {{','.join(errors)}} 
        </div>
        {% endfor %}
        <!--오류표시 끝-->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or ''}}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{form.content.data or ''}}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</botton>
    </form>
</div>

{%endblock%}

pybo/templates/question/question_list.html
{%extends "base.html"%}
{%block content%}
<div class="container my-3">
    <!--검색 창-->
    <div class="row justify-content-between my-3"> <!--between: 양쪽정렬-->
        <div class="col-2">
            <select class="form-control so">
                <!--정렬 기준 나열-->
                <option value="recent" {%if so=='recent'%}selected{%endif%}>최신순</option>
                <option value="recommend" {%if so=='recommend'%}selected{%endif%}>추천순</option>
                <option value="popular" {%if so=='popular'%}selected{%endif%}>인기순</option>
            </select> 
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{kw or ''}}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">
                    찾기
                </button>
            </div>
        </div>
    </div>

    <table class="table">
      <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
      </thead>  
      <tbody>
        {% if question_list %}
        {%for question in question_list.items %}
        <tr class="text-center">
            <td>{{question_list.total-((question_list.page-1)*question_list.per_page)-loop.index0}}</td>
            <td>
                {%if question.voter|length>0%}
                <span class="badge badge-warning px-2 py-1">
                    {{question.voter|length}}
                </span>
                {%endif%}
            </td>
            <td class="text-left">
                <a href="{{url_for('question.detail',question_id=question.id)}}">
                    {{question.subject}}
                </a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small ml-2">{{question.answer_set|length}}</span>
                {%endif%}
            </td>
            <td> 
                <!--글쓴이 표시-->
                {{question.user.username}}
            </td>
            <td>
                <!--작성일시 표시-->
                {{question.create_date|datetime}}
            </td>
        </tr>
        {%endfor%}
        {%else%}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {%endif%}
    </tbody>
    </table>
    
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?=page{{question_list.prev_num}}" href="#">이전</a>
        </li>
        {%else%}
        <!--이전 페이지가 없을 때 이전 링크를 비활성화한다-->
        <li class="page-item aria-disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {%endif%}
        <!--페이지를 돌아가면서 해당 페이지로 이동할 수 있는 링크 생성-->
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" hhref="?page={{page_num}}" href="#">{{page_num}}</a>
                </li>
                {%else%}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{page_num}}</a>    
                </li>
                {%endif%}
            {%else%}
                <!--페이지 번호가 없을 경우 ... 을 표시-->
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
            {%endif%}
        {%endfor%}            
        <!--다음 페이지-->
        {%if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.next_num}}">다음</a>
        </li>
        {%else%}
        <!--다음 페이지가 없을 때 다음 링크를 비활성화한다-->
        <li class="page-item disabled">
            <a class="page-link" data-page="{{question_list.next_num}}" href="#">다음</a>
        </li>
        {%endif%}
    </ul>
    <!--페이징 처리 끝-->
    <a href="{{url_for('question.create')}}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>
<!--질문 입력 폼-->
<form id="searchForm" method="get" action="{{url_for('question._list')}}">
    <input type="hidden" id="kw" name="kw" value="{{kw or ''}}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{so}}">
</form>
{%endblock%}

<!--질문 목록 페이지에서 사용할 자바스크립트-->
{%block script%}

<script type="text/javascript">
    $(document).ready(function(){
        //페이지
        $(".page-link").on('click',function(){
            $("#page").val($("this").data("page"));
            $("#searchForm").submit();
        });

        //검색 키워드
        $("#btn_search").on('click',function(){
            $("#kw").val($(".kw").val());
            $("#page").val(1);//검색 버튼을 클릭할 경우 1페이지부터 조회한다
            $("#searchForm").submit();
        });

        //정렬 기준
        $(".so").on('change',function(){
            $("#so").val($(this).val());
            $("#page").val(1);//정렬 p기준을 변경할 경우 1페이지부터 조회한다
            $("searchForm").submit();
        });
    });
</script>

{%endblock%}